name: GAPQuickcheck
version: 0.1
date: 2018-05-22
description: |
    Library for property testing in GAP.

authors:
    - name: Victor Vasilyev
      url: TODO

maintainers:
    - name: Victor Vasilyev
      url: TODO

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Digraphs"
      version: ">= 0.12.1"
      url: "https://gap-packages.github.io/Digraphs"

www: https://gap-packages.github.io/GAPQuickcheck/
readme: README.md
packageinfo: https://gap-packages.github.io/GAPQuickcheck/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/GAPQuickcheck/releases/download/v0.1/GAPQuickcheck-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
