################################################################################################
##
#W randomgen.gd     GAP Quickcheck     Victor Vasilyev
##
## Declaration of random argument generator functions for the GAP Quickcheck package.
##
#Y Copyright (C) 2018 University of St. Andrews, North Haugh, St. Andrews, Fife
#Y                                                KY16 9SS, Scotland
##


################################################################################################
##
#F QuickcheckInt(<max>, <randomsource>) . . . . . generate a random integer
##
## <#GAPDoc Label="QuickcheckInt">
## <ManSection>
## <Func Name="QuickcheckInt" Arg="max,randomsource"/>
##
## <Desription>
## generates an integer of maximum size <max> with the
## random source <randomsource>.
## </Desription>
## </ManSection>
## <#/GAPDoc>
##                                              
DeclareGlobalFunction("QuickcheckInt");

################################################################################################
##
#F QuickcheckList(<generator>) . . . . . make a generator for a random list
##
## <#GAPDoc Label="QuickcheckList">
## <ManSection>
## <Func Name="QuickcheckList" Arg="generator"/>
##
## <Desription>
## returns a function that, given a maximum size and a random source,
## generates a list of objects generated by the <generator>. <generator> must take two arguments,
## a maximum size and a random source.
## </Desription>
## </ManSection>
## <#/GAPDoc>
##                                              
DeclareGlobalFunction("QuickcheckList");

################################################################################################
##
#F QuickcheckSet(<generator>) . . . . . make a generator for a random set
##
## <#GAPDoc Label="QuickcheckSet">
## <ManSection>
## <Func Name="Quickcheckset" Arg="generator"/>
##
## <Desription>
## returns a function that, given a maximum size and a random source,
## generates a set of objects generated by the <generator>. <generator> must take two arguments,
## a maximum size and a random source.
## </Desription>
## </ManSection>
## <#/GAPDoc>
##                                              
DeclareGlobalFunction("QuickcheckSet");
DeclareGlobalFunction("QuickcheckObject");
DeclareGlobalFunction("QuickcheckRecord");
DeclareGlobalFunction("QuickcheckPermutation");
DeclareGlobalFunction("QuickcheckAbelianGroup");
DeclareGlobalFunction("QuickcheckQuaternionGroup");
DeclareGlobalFunction("QuickcheckDihedralGroup");
DeclareGlobalFunction("QuickcheckPermutationGroup");
DeclareGlobalFunction("QuickcheckCoset");
DeclareGlobalFunction("QuickcheckDigraph");
DeclareGlobalFunction("QuickcheckCyclicGroup");
DeclareGlobalFunction("QuickcheckFreeAbelianGroup");
DeclareGlobalFunction("QuickcheckGroup");
DeclareGlobalFunction("QuickcheckSmallPermutationGroup");
